services:
  db:
    image: postgres:16-alpine
    container_name: ladno_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ladno_db
      POSTGRES_USER: ladno_user
      POSTGRES_PASSWORD: ladno_password
    ports:
      - "5433:5432"
    volumes:
      - ladno_postgres_data:/var/lib/postgresql/data

volumes:
  ladno_postgres_data:
