# Generated by Django 6.0.4 on 2026-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BreathingPractice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "cycles",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="Количество циклов"
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="Длительность в минутах"
                    ),
                ),
                (
                    "instruction",
                    models.TextField(blank=True, verbose_name="Инструкция"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "Дыхательная практика",
                "verbose_name_plural": "Дыхательные практики",
            },
        ),
    ]
