# Generated by Django 6.0.4 on 2026-05-04 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Не более 400 символов.",
                max_length=400,
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Заметка",
            ),
        ),
    ]
