# Generated by Codex on 2026-05-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="anxiety_score",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1 — низкая, 5 — высокая",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Тревожность",
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="factors",
            field=models.CharField(
                blank=True,
                help_text="Например: сон, работа, спорт, кофе, общение",
                max_length=255,
                verbose_name="Факторы дня",
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="gratitude",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="За что благодарны",
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="sleep_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(24),
                ],
                verbose_name="Сон, часов",
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="stress_score",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="1 — спокойно, 5 — очень напряжённо",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Стресс",
            ),
        ),
        migrations.AddConstraint(
            model_name="moodentry",
            constraint=models.UniqueConstraint(
                fields=("user", "date"),
                name="unique_mood_entry_per_user_date",
            ),
        ),
    ]
