# Generated by Codex on 2026-05-05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_extend_mood_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="До 400 символов",
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Заметка",
            ),
        ),
    ]
