# Generated by Django 6.0.4 on 2026-05-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_alter_moodentry_note"),
        ("mood", "0003_limit_note_and_edit_window"),
    ]

    operations = []
