# Generated by Django 6.0.4 on 2026-05-12 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0004_merge_20260512_2107"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="moodentry",
            name="unique_mood_entry_per_user_date",
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="anxiety_score",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Оценка уровня тревожности от 1 до 5.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Тревожность",
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="factors",
            field=models.TextField(
                blank=True,
                help_text="Что повлияло на состояние. Не более 400 символов.",
                max_length=400,
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Факторы",
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="gratitude",
            field=models.TextField(
                blank=True,
                help_text="Что хорошего произошло сегодня. Не более 400 символов.",
                max_length=400,
                validators=[django.core.validators.MaxLengthValidator(400)],
                verbose_name="Благодарность",
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="sleep_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Количество часов сна.",
                max_digits=4,
                null=True,
                verbose_name="Сон, часов",
            ),
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="stress_score",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Оценка уровня стресса от 1 до 5.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Стресс",
            ),
        ),
    ]
