# Generated by Django 6.0.4 on 2026-05-16 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0005_add_extended_mood_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="moodentry",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_mood_entry_per_user_date"
            ),
        ),
    ]
