# Generated by Django 6.0.4 on 2026-04-25 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Светлая"), ("dark", "Тёмная")],
                        default="light",
                        max_length=20,
                        verbose_name="Тема",
                    ),
                ),
                (
                    "reminder_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Напоминания включены"
                    ),
                ),
                (
                    "reminder_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время напоминания"
                    ),
                ),
                (
                    "ai_analysis_enabled",
                    models.BooleanField(default=True, verbose_name="AI-анализ включён"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя",
                "verbose_name_plural": "Настройки пользователей",
            },
        ),
    ]
