# Generated by Django 6.0.4 on 2026-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="gender",
            field=models.CharField(
                choices=[
                    ("not_specified", "Не указывать"),
                    ("male", "Мужской"),
                    ("female", "Женский"),
                ],
                default="not_specified",
                max_length=20,
                verbose_name="Пол",
            ),
        ),
    ]
