# Generated by Django 6.0.4 on 2026-05-16 19:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="aireport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="aireport",
            name="summary",
            field=models.TextField(verbose_name="Резюме"),
        ),
        migrations.AddConstraint(
            model_name="aireport",
            constraint=models.UniqueConstraint(
                fields=("user", "period_start", "period_end"),
                name="unique_ai_report_per_user_period",
            ),
        ),
    ]
